export const ENV_STR = {
  NEXT_PUBLIC_APPWRITE_URL: String(process.env.NEXT_PUBLIC_APPWRITE_URL),
  NEXT_PUBLIC_ENDPOINT: String(process.env.NEXT_PUBLIC_ENDPOINT),
  NEXT_PUBLIC_DATABASE_ID: String(process.env.NEXT_PUBLIC_DATABASE_ID),
  NEXT_PUBLIC_COLLECTION_ID_PROFILE: String(process.env.NEXT_PUBLIC_COLLECTION_ID_PROFILE),
  NEXT_PUBLIC_COLLECTION_ID_POST: String(process.env.NEXT_PUBLIC_COLLECTION_ID_POST),
  NEXT_PUBLIC_COLLECTION_ID_LIKE: String(process.env.NEXT_PUBLIC_COLLECTION_ID_LIKE),
  NEXT_PUBLIC_COLLECTION_ID_COMMENT: String(process.env.NEXT_PUBLIC_COLLECTION_ID_COMMENT),
  NEXT_PUBLIC_BUCKET_NAME: String(process.env.NEXT_PUBLIC_BUCKET_NAME),
  NEXT_PUBLIC_BUCKET_ID: String(process.env.NEXT_PUBLIC_BUCKET_ID),
  NEXT_PUBLIC_PLACEHOLDER_DEAFULT_IMAGE_ID: String(process.env.NEXT_PUBLIC_PLACEHOLDER_DEAFULT_IMAGE_ID)
}